### PR TITLE
Don't set free tickets to be automatically approved.

### PR DESCRIPTION
**Pull request by Pebblo**
In short if you have a free ticket and users sign up to be on the waitlist, if a space becomes available and their registration is Approved they don't get an email stating they have been approved.

The 'Registration Promoted From Wait List Notification' is sent but the registration is already approved so even when the user finalizes the registration from the link in the email, no email is triggered.

For now I think its best if we set the add-on to treat all waitlist registrations the same and just have them set to pending payment (or whatever DRS they have), if the user then uses the link in the email they can finalize the reg and receive the reg approved email.

This change is basically just removing a check for a free txn, everything else is core waitlist behaviour.

## How has this been tested
Create an event with a datetime/ticket limit of 1 with a free ticket and register onto it (make sure it set up to accept waitlist registrations)

Add a least 1 waitlist registration to the event.

Now cancel the first 'Approved' registration and the waitlist registration should be set to pending payment (assuming you have that set as the DRS).

View the message activity table and open up the promotion email, click the link and finalize, you should now have an Approved registration.... check the Reg Approved emails send.

Note in master when you cancelled the approved registration is would automatically set the next waitlist reg to Approved and send them the email to finalize... which then basically did nothing.

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by joshfeck** [comment]
I guess I don't have a preference either way. The challenging part of this seems to be how to explain why a free ticket can get promoted to status of "Pending Payment". 

If we go forward with this change it looks like the unit tests need to updated as well.

**Comment by tn3rb** [comment]
not that I'm trying to open that can of worms, but it does seem like this is partially an issue with insufficient registration status options doesn't it? 

Like `Pending Payment` should be broken up into `Requires Payment` and `Pending Confirmation` (or `Pending Acceptance` or whatever).

Something like `Pending Confirmation` could serve double duty as a status for use with RSVPs

**Comment by Pebblo** [comment]
Yeah, a 'Pending Confirmation' status would be great for a few different use cases.

We've had uses alter the output of 'Pending payment' to a few different strings but most often just 'Pending'

**Comment by sethshoultes** [comment]
Would adding these labels change anything as far as functionality? I would assume that using any of these labels would apply a pending status to the registration.

**Comment by Pebblo** [comment]
Tbh, I'm not sure I follow what you mean Seth but I'll add my understanding and Brent will confirm or burn ;)

Technically the registration status is set to have a status of RPP which has a 'label' of 'Pending Payment' and you can easily change that with a snippet, however changing that is site-wide meaning if we change it to 'Pending Confirmation' then it no longer fits true 'Pending Payment' registrations, right?

I don't think we can set multiple labels on status but we can add additional registration statuses (say 'Registration Statuses' that 3 times fast!)

So we would need another registration status that could essentially be treated exactly the same as 'Pending Payment' but was intended as an 'external' status from checkout (and so not set by SPCO in its current flow) which can then be customized to suit whatever the user needs it for. 

Say we had a status of RPC (Registration Pending Confirmation) which had the label 'Pending Confirmation' and the Waitlist add-on set the above registrations to that in this situation, the label for that status can be set to whatever you want because it's not used as part of our normal flow.

**Comment by joshfeck** [comment]
I guess one way this could be explained is, the status is RPP. Which, when it's a paid ticket means "Registration Pending Payment". When it's a free ticket, RPP can mean "Registration Promoted & Pending"

**Pull request closed without merging**
